dist: trusty
sudo: false
language: elixir
elixir:
  - 1.11
otp_release:
  - 22.3
addons:
  postgresql: '9.6'
  apt:
    packages:
      - postgresql-9.6-postgis-2.3
services:
  - postgresql
before_script:
  - psql -c 'create database strabo_test;' -U postgres
  - psql -c 'create extension postgis;' -U postgres -d strabo_test
script:
  - mix test
before_deploy:
  - mix compile
deploy:
  skip_cleanup: true
  provider: script
  script: mix hex.publish --yes
  on:
    tags: true
